# Site settings
title: Mauricio Vieira
header-img: img/home-bg.jpg
email: contact@mauriciovieira.net
copyright_name: MauricioVieira.net
description: "A new tech blog (again)"
baseurl: ""
url: "http://mauriciovieira.github.io"
twitter_username: mauriciovieira
github_username:  mauriciovieira
facebook_username:  mbcvieira
email_username:  contact@mauriciovieira.net

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-83385206-1

# Disqus
disqus: mauriciovieira-github-io

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
